version: '3.1'

services: 
  db:
    image: mysql
    container_name: mysql
    restart: always
    tty: true
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}